name: "Tool Versions"
description: "Output version numbers with .tool-versions file."
inputs:
  path:
    description: "path of .tool-versions file"
    required: true
    default: ".tool-versions"
outputs:
  nodejs:
    description: "version of nodejs"
  ruby:
    description: "version of ruby"
  elixir:
    description: "version of elixir"
  erlang:
    description: "version of erlang"
runs:
  using: "node12"
  main: "dist/index.js"
