name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        id: versions
        with:
          path: ".tool-versions"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}
      - run: npm ci
      - run: npm test
